name: Build 控件 EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller uiautomation  # 明确安装 pyinstaller

    - name: Create EXE with PyInstaller
      run: |
        python -m PyInstaller --onefile --hidden-import=uiautomation ui.py  # 使用模块调用方式

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ui-exe
        path: ./dist/ui.exe
        retention-days: 7